name: Build Pi-DJ OS

on:
  push:
    branches:
      - main
      - arm-runner

jobs:
  build:
    # Need to run on a self-hosted runner because `ping` does not work in the GitHub Actions runner
    # thus causing `dietpi-software` to fail to test network connectivity and not install any software.
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: dietpi:rpi_armv8_bullseye
          cpu: cortex-a53
          image_additional_mb: 500
          commands: |
            set +x
            echo
            echo ">--------------------------------------------------------------------------------------------------<"
            echo "> Building Pi-DJ                                                                                    "
            echo ">--------------------------------------------------------------------------------------------------<"
            echo

            ./dietpi/build.sh

            echo
            echo ">--------------------------------------------------------------------------------------------------<"
            echo "> Done!                                                                                             "
            echo ">--------------------------------------------------------------------------------------------------<"
            echo

      - name: Compress the release image
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/arm-runner'
        run: |
          mv ${{ steps.build_image.outputs.image }} pi-dj-${{ github.ref_name }}.img
          xz -0 -T 0 -v pi-dj-${{ github.ref_name }}.img

      - name: Upload release image
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/arm-runner'
        with:
          name: pi-dj-${{ github.ref_name }}.img.xz
          path: pi-dj-${{ github.ref_name }}.img.xz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        with:
          draft: github.ref == 'refs/heads/main'
          prerelease: true
          # body: "" # TODO
          files: |
            # TODO: update files after building
            Release.txt
            LICENSE
