name: Build Pi-DJ OS

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install build dependencies
        run: sudo apt-get install coreutils quilt parted kpartx qemu-utils qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc

      - name: Build Pi-DJ
        run: cd os && DOCKER=false sudo ./build.sh image

      - uses: actions/upload-artifact@v2
        with:
          name: images
          path: deploy/*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: packages-info
          path: deploy/*.info
